@baseUrl=http://localhost:3000/catalog
@id=2

### Lire tous les produits
GET {{baseUrl}}/products HTTP/1.1

### Lire toutes les catégories
GET {{baseUrl}}/categories HTTP/1.1

### Lire une categorie avec ses produits
GET {{baseUrl}}/category/{{id}} HTTP/1.1

### Lire un produit
GET {{baseUrl}}/product/{{id}} HTTP/1.1